backend:
  name: git-gateway
  repo: uzairmirza90/prix-cms-sample
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/images/posts
public_folder: /images
collections:
  - name: 'blogs'
    label: 'Blogs'
    folder: "data/blogs"
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'string' }
      - { label: 'Description', name: 'excerpt', widget: 'string'}
      - { label: 'Cover Image', name: 'cover_image', widget: 'string'}
      - { label: 'Body', name: 'body', widget: 'markdown' }
